version: '2'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi  # use "raspberry-pi" instead of "latest" for arm devices
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Seoul
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8081
    volumes:
      - ./homebridge:/homebridge
  # api:
  #   image: node:11.4.0
  #   user: node
  #   working_dir: ${NODE_WORKDIR}
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   devices:
  #     - /dev/lirc0:/dev/lirc0
  #   volumes:
  #     - ./:${NODE_WORKDIR}
  #     - /dev/lirc0:/dev/lirc0
  #   expose:
  #     - 8080
  #   command: yarn start
  #   network_mode: host